### ISSUE TITLE
How to use a proxy

### ISSUE THREAD

**Issue by ronnievisser** [cfv1000/phantomjs-cloud#1]
Hi,

How can we use a proxy with this exactly?

**Comment by flaviu-chelaru** [comment]
Hello - this is just basic representation of requests. If you want to perform advanced HTTP requests, you will need an HTTP client that can support that. You can try Guzzle or similar clients

**Comment by flaviu-chelaru** [comment]
http://docs.guzzlephp.org/en/stable/request-options.html#proxy - you can use the official guzzle documentation for proxy usage. 

You can also perform these requests using alternative HTTP clients https://packagist.org/?q=http%20client&p=0
